apiVersion: v2
name: example
type: application
version: 1.0.0
dependencies:
  - name: traefik
    version: 39.0.8
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: traefik
  - name: prometheus
    version: 27.5.1
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: prometheus
    mcs_dep_index: 0
  - name: opencost
    version: 2.3.2
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: opencost
    mcs_dep_index: 1
