traefik:
  traefik:
    deployment:
      kind: DaemonSet
    ports:
      web:
        port: 8000
        hostPort: 80
      websecure:
        port: 8443
        hostPort: 443

prometheus:
  prometheus:
    prometheus-pushgateway: { enabled: false }
    alertmanager: { enabled: false }
    extraScrapeConfigs: |
      - job_name: opencost
        honor_labels: true
        dns_sd_configs: [{ names: [opencost.opencost], type: 'A', port: 9003 }]

opencost:
  opencost:
    opencost:
      prometheus:
        internal:
          namespaceName: opencost
      ui:
        ingress:
          enabled: true
          hosts: [{ host: 'opencost.example.com', paths: ['/'] }]
