prometheus:
  prometheus:
    prometheus-pushgateway: { enabled: false }
    alertmanager: { enabled: false }
    extraScrapeConfigs: |
      - job_name: opencost
        honor_labels: true
        dns_sd_configs: [{ names: [opencost.opencost], type: 'A', port: 9003 }]

opencost:
  opencost:
    opencost:
      prometheus:
        internal:
          namespaceName: prometheus
