apiVersion: v2
name: helm-slurm-cluster
description: A Helm chart that references the official "helm-slurm-cluster" Helm chart.
type: application
version: 4.1.11
dependencies:
  - name: helm-slurm-cluster
    version: 4.1.11
    repository: oci://cr.eu-north1.nebius.cloud/soperator
