charts:
  gpu-operator:
  - version: v24.9.2
    appVersion: v24.9.2
  - version: v25.3.0
    appVersion: v25.3.0
  - version: v25.10.0
    appVersion: v25.10.0
  - version: v25.10.1
    appVersion: v25.10.1
  - version: v26.3.1
    appVersion: v26.3.1
