apiVersion: v2
name: lws
description: A Helm chart that references the official "lws" Helm chart.
type: application
version: 0.11.1
dependencies:
  - name: lws
    version: 0.11.1
    repository: oci://registry.k8s.io/lws/charts
