traefik:
  traefik:
    deployment:
      kind: DaemonSet
    ports:
      web:
        port: 8000
        hostPort: 80
      websecure:
        port: 8443
        hostPort: 443

kube-prometheus-stack:
  kube-prometheus-stack:
    prometheus:
      prometheusSpec:
        maximumStartupDurationSeconds: 300
      ingress:
        enabled: true
        hosts: ['prometheus.example.com']
    grafana:
      # default login - admin:prom-operator
      ingress:
        enabled: true
        hosts: ['']
