apiVersion: v2
name: example
type: application
version: 1.0.0
dependencies:
  - name: traefik
    version: 39.0.5
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: kube-prometheus-stack
    version: 81.6.3
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: alloy
    version: 1.6.1
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: loki
    version: 6.53.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
