apiVersion: v2
name: example
type: application
version: 6.20.0
dependencies:
  - name: traefik
    version: 39.0.5
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: open-webui
    version: 8.12.3
    repository: oci://ghcr.io/k0rdent/catalog/charts
