apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k0rdent-catalog-web.fullname" . }}
  labels:
    {{- include "k0rdent-catalog-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "k0rdent-catalog-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k0rdent-catalog-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: catalog-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
