apiVersion: k0rdent.mirantis.com/{{ $.Values.k0rdentApiVersion }}
kind: Credential
metadata:
  name: remote-credential
spec:
  identityRef:
    apiVersion: v1
    kind: Secret
    name: remote-ssh-key
    namespace: {{ .Release.Namespace }}
