apiVersion: v2
name: example
type: application
version: 1.0.0
dependencies:
  - name: cert-manager
    version: 1.20.2
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: kserve-crd
    version: v0.18.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_dep_index: 0
  - name: kserve-resources
    version: v0.18.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_dep_index: 1
