traefik:
  traefik:
    deployment:
      kind: DaemonSet
    ports:
      web:
        port: 8000
        hostPort: 80
      websecure:
        port: 8443
        hostPort: 443
      pg:
        port: 5432
        hostPort: 5432

postgresql:
  postgresql:
    global:
      security:
        allowInsecureImages: true
    image:
      repository: bitnamilegacy/postgresql
    auth:
      postgresPassword: pgpasswd
      username: user
      password: passwd
      database: pgdb
    readReplicas:
      replicaCount: 2
    extraDeploy:
    - apiVersion: traefik.io/v1alpha1
      kind: IngressRouteTCP
      metadata:
        name: pg
        namespace: postgresql
      spec:
        entryPoints:
          - pg
        routes:
          - match: HostSNI(`*`)
            services:
              - name: postgresql
                port: 5432
