traefik:
  traefik:
    deployment:
      kind: DaemonSet
    ports:
      web:
        port: 8000
        hostPort: 80
      websecure:
        port: 8443
        hostPort: 443

argo-cd:
  argo-cd:
    global:
      domain: ''
    configs:
      params:
        server.insecure: true
    server:
      ingress:
        enabled: true
