apiVersion: v2
name: example
type: application
version: 1.0.0
dependencies:
  - name: jupyterhub
    version: 4.2.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: traefik
    version: 39.0.5
    repository: oci://ghcr.io/k0rdent/catalog/charts
