charts:
  ingress-nginx:
  - version: 4.11.5
    appVersion: 1.11.5
  - version: 4.12.3
    appVersion: 1.12.3
  - version: 4.13.2
    appVersion: 1.13.2
  - version: 4.14.3
    appVersion: 1.14.3
  - version: 4.15.1
    appVersion: 1.15.1
