st-charts:
- name: opentelemetry-operator
  dep_name: opentelemetry-operator
  version: 0.99.2
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
- name: opentelemetry-operator
  dep_name: opentelemetry-operator
  version: 0.105.1
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
