charts:
  base:
  - version: 1.26.2+tetrate2
    appVersion: 1.26.2-tetrate2
  - version: 1.27.1+tetrate3
    appVersion: 1.27.1-tetrate3
  - version: 1.28.2+tetrate0
    appVersion: 1.28.2-tetrate0
  istiod:
  - version: 1.26.2+tetrate2
    appVersion: 1.26.2-tetrate2
  - version: 1.27.1+tetrate3
    appVersion: 1.27.1-tetrate3
  - version: 1.28.2+tetrate0
    appVersion: 1.28.2-tetrate0
  gateway:
  - version: 1.26.2+tetrate2
    appVersion: 1.26.2-tetrate2
  - version: 1.27.1+tetrate3
    appVersion: 1.27.1-tetrate3
  - version: 1.28.2+tetrate0
    appVersion: 1.28.2-tetrate0
