apiVersion: v2
name: nirmata-kyverno
description: A Helm chart that references the official "nirmata-kyverno" Helm chart.
type: application
version: 3.8.3
dependencies:
  - name: kyverno
    version: 3.8.3
    repository: https://nirmata.github.io/kyverno-charts/
