apiVersion: v2
name: agent-gateway-crds
description: A Helm chart that references the official "agent-gateway-crds" Helm chart.
type: application
version: 1.1.0
dependencies:
  - name: agentgateway-crds
    version: 1.1.0
    repository: oci://cr.agentgateway.dev/charts
