apiVersion: k0rdent.mirantis.com/v1alpha1
kind: MultiClusterService
metadata:
  name: amd
spec:
  clusterSelector:
    matchLabels:
      group: demo
  serviceSpec:
    services:
    - template: cert-manager-1-17-2
      name: cert-manager
      namespace: amd
      values: |
        cert-manager:
          crds:
            enabled: true
    - template: amd-gpu-operator-v1-2-0
      name: amd-gpu-operator
      namespace: amd
