apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: azure-demo-cluster
  namespace: kcm-system
  labels:
    type: azure
    group: demo
spec:
  template: {{ azure_standalone_cp }}
  credential: azure-credential
  config:
    controlPlaneNumber: 7
    location: "westus"
    subscriptionID: AZURE_SUB_ID
    controlPlane:
      vmSize: Standard_A4_v2
    worker:
      vmSize: Standard_A16_v2
      rootVolumeSize: 512
    workersNumber: 16
