aws:
  small: clds/aws-cld-small.yaml
  medium: clds/aws-cld-medium.yaml
  large: clds/aws-cld-large.yaml
azure:
  small: clds/azure-cld-small.yaml
  medium: clds/azure-cld-medium.yaml
  large: clds/azure-cld-large.yaml
gcp:
  small: clds/gcp-cld-small.yaml
  medium: clds/gcp-cld-medium.yaml
  large: clds/gcp-cld-large.yaml
openstack:
  small: clds/openstack-cld-small.yaml
  medium: clds/openstack-cld-medium.yaml
  large: clds/openstack-cld-large.yaml
