apiVersion: v2
name: agent-gateway-crds
description: A Helm chart that references the official "agent-gateway-crds" Helm chart.
type: application
version: v2.2.1
dependencies:
  - name: agentgateway-crds
    version: v2.2.1
    repository: oci://cr.agentgateway.dev/charts
