st-charts:
- name: traefik
  dep_name: traefik
  version: 39.0.8
  repository: https://traefik.github.io/charts
- name: traefik
  dep_name: traefik
  version: 40.3.0
  repository: https://traefik.github.io/charts
