apiVersion: v2
name: example
type: application
version: 1.0.0
dependencies:
  - name: agent-gateway-crds
    version: 1.1.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: agent-gateway
    version: 1.1.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
