apiVersion: v2
name: example
type: application
version: 4.0.1
dependencies:
  - name: traefik
    version: 39.0.5
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: msr
    version: 4.13.6
    repository: oci://ghcr.io/k0rdent/catalog/charts
