traefik:
  traefik:
    deployment:
      kind: DaemonSet
    ports:
      web:
        port: 8000
        hostPort: 80
      websecure:
        port: 8443
        hostPort: 443

msr:
  msr:
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: "wildcard-tls"
      ingress:
        controller: default
        hosts:
          core: msr4.example.url
    externalURL: msr4.example.url
