traefik:
  traefik:
    deployment:
      kind: DaemonSet
    ports:
      web:
        port: 8000
        hostPort: 80
      websecure:
        port: 8443
        hostPort: 443

harbor:
  harbor:
    externalURL: http://harbor.local
    expose:
      ingress:
        hosts:
          core: harbor.local
      tls:
        enabled: false
