apiVersion: v2
name: example
type: application
version: 1.0.0
dependencies:
  - name: traefik
    version: 39.0.5
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: traefik
  - name: tempo
    version: 1.24.4
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: tracing
  - name: opentelemetry-collector
    version: 0.145.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: tracing
  - name: istio-base
    version: 1.28.3
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: istio-system
  - name: istiod
    version: 1.28.3
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: istio-system
  - name: raw
    version: 2.0.2
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: raw
  - name: kube-prometheus-stack
    version: 81.6.3
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: prometheus
    mcs_name: prometheus
